name: Node.js CI

on:
  push:
    branches: [ main ]
    paths-ignore:
      - 'src/.internal/**'
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm test
      env:
        CI: true
    - name: Coveralls GitHub Action
      uses: coverallsapp/github-action@v2.2.3